### DISCUSSION TITLE
How to get the setpoint?

### DISCUSSION THREAD

**Discussion by ticpu** [bigmoby/fglair_for_homeassistant#209] [Q&A] [answered]
I am trying to setup an automation to move our around the house. The goal is to enable Fan+Boost when the room temperature 2°C above setpoint (and outside temperature is below 0°C).

Then another automation would restore Heat mode when temperature falls .5 °C below the setpoint.

Only issue is that I don't seem to be able to read the setpoint, only set it.  I could setup a variable for that I guess but I don't know how to yet.

Is there a way that I might've missed to read the setpoint like I can see in the UI in automations?

**Comment by ticpu** [comment, marked as answer]
What I did learn today:
- HA does not allow maths in above/below fields.
- Temperatures do not appear as sensor entities, so they're not easy to add as comparison values.
- Creating helpers can make those values available as sensors.
- Even if you have sensors, you're still stuck with «no maths in above/below» and creating helpers for offset values is cumbersome.
- Some documentation use 'action' instead of 'service' and it is wrong.
- Using attributes is a pain compared to sensors.

Here is an example for what I'm trying to achieve:
```yaml
alias: Fan Control - Part 1 - Turn On Fan
description: Turn on fan when temperature is too high
triggers:
- trigger: numeric_state
  entity_id:
  - sensor.hvac_set_point_delta
  above: 2
conditions:
- condition: numeric_state
  entity_id: sensor.saint_georges_low_temperature
  below: 0
actions:
- data_template:
    entity_id: input_number.hvac_last_target_temperature
    value: "{{ state_attr('climate.ac_uty_a408eac75ec9', 'temperature') }}"
  action: input_number.set_value
- data_template:
    entity_id: input_text.hvac_last_fan_orientation
    value: "{{ state_attr('climate.ac_uty_a408eac75ec9', 'swing_mode') }}"
  action: input_text.set_value
- data:
    hvac_mode: fan_only
    entity_id: climate.ac_uty_a408eac75ec9
  action: climate.set_hvac_mode
- delay:
    seconds: 2
- action: climate.set_swing_mode
  data:
    swing_mode: Vertical_7
  target:
    entity_id: climate.ac_uty_a408eac75ec9
- action: climate.set_fan_mode
  data:
    fan_mode: high
  target:
    entity_id: climate.ac_uty_a408eac75ec9
- delay:
    seconds: 2
- action: climate.set_preset_mode
  data:
    preset_mode: boost
  target:
    entity_id: climate.ac_uty_a408eac75ec9
mode: single
```

I'll close this discussion once I get a couple triggers as I'd like to make sure it fully works first.
