### ISSUE TITLE
Current_temperture not updating

### ISSUE THREAD

**Issue by grahamr** [bigmoby/fglair_for_homeassistant#40]
Version 0.2.7 installed

Home Assistant 2023.3.6
Supervisor 2023.03.3
Operating System 9.5
Frontend 20230309.1 l

Connected to a ducted air source heat pump. 

The current_temperature is not updating (has been reading 22.6 for 24+ hours) but the temperature (set temp) is updating, as well as fan modes and heat modes

**Comment by bigmoby** [comment]
Hi @grahamr have you tried to set the log into debug and analyze it? Probably the current temperature is not updated and sent by server and the integration itself is right.

**Comment by grahamr** [comment]
I have not yet, I noticed there was a pr a bit back to add logging for
this.

Is that just the main HA log or is there a tweak to make to the code for
the addin to confirm?

I did notice that my app and thermostat did both show the right indoor
temp, but I’ll dig into logs next

**Comment by bigmoby** [comment]
I don't know what the PR you're referring to, but please configure HA as follows:

```
logger:
  default: critical
  logs:
    homeassistant.components.climate: debug
    custom_components.fglair_heatpump_controller.climate: debug
```

and please after a HA restart post here your fglair logs (please obfuscate personal information if any).
