### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by jfisbein** [bigmoby/fglair_for_homeassistant#59]
I really don't know what happened but in one of the restarts I made last week due to some integration upgrade. fglair_for_homeassistant stopped working.

I configured the logger for the fglair_for_homeassistant integration in debug mode and extracted the log.

Here it's my config
```
## FGLAIR Integration
climate:
  - platform: fglair_heatpump_controller
    username: !secret FGLAIR_USER
    password: !secret FGLAIR_PASS
    region: "eu"
    tokenpath: "token.txt"
```

I already checked that credential secrets are correctly setup, and also checked I have access to my fglair account through the offical mobile app.

Attached are the relevant log lines
[home-assistant_2023-10-02T16-28-37.449Z.log](https://github.com/bigmoby/fglair_for_homeassistant/files/12784779/home-assistant_2023-10-02T16-28-37.449Z.log)

My installation is HAOS with those versions:
```
Home Assistant 2023.9.3
Supervisor 2023.09.2
Operating System 10.5
Frontend 20230911.0 - latest
```

Any idea about how to fix it?
