### ISSUE TITLE
Acces to entities 

### ISSUE THREAD

**Issue by fati78** [bigmoby/fglair_for_homeassistant#8]
Hello!
Thank you for a very useful integration.

Is it possible to access enteties?
For example 
Changing target temperature from an automation script or using target temperature as a sensor.

**Comment by fati78** [comment]
> I am not author. But I'll try answer this. Target temperature is a number you define yourself. It doesn't involve a sensor. This uses pyfujitsu library, which I recall doesn't have api for sensors. But, for automation, you could use another external sensor and use node red to define some logic yourself.

Thanx for the reply:

Here is my configuration and it is working fine:
```
climate:
  - platform: fglair_heatpump_controller
    username: ******************
    password: ***********
    region: 'eu'
    tokenpath: 'token.txt'
```

Available attributes for the platform:
```
hvac_modes:
  - heat
  - cool
  - auto
  - dry
  - fan_only
  - 'off'
min_temp: 16
max_temp: 30
target_temp_step: 1
fan_modes:
  - auto
  - low
  - medium
  - high
  - diffuse
swing_modes:
  - 'off'
  - 'on'
  - vertical
  - horizontal
current_temperature: 22.8
temperature: 22
fan_mode: high
swing_mode: 'off'
icon: mdi:air-conditioner
friendly_name: FujiElectric
supported_features: 41
```


What i want is to create a sensor (or alias) for some of the attributes for example `current_temperature` and use it directly in graphs, automations and so one ...
